"use client"

import { useLoader } from "@react-three/fiber"
import { TextureLoader, RepeatWrapping } from "three"
import { useMemo } from "react"

// Texture data URLs for wood grains and fabric patterns
const WOOD_GRAIN_TEXTURES = {
  oak: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAZABkAAD/7AARRHVja3kAAQAEAAAAPAAA/+4ADkFkb2JlAGTAAAAAAf/bAIQABgQEBAUEBgUFBgkGBQYJCwgGBggLDAoKCwoKDBAMDAwMDAwQDA4PEA8ODBMTFBQTExwbGxscHx8fHx8fHx8fHwEHBwcNDA0YEBAYGhURFRofHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8f/8AAEQgAQABAAwERAAIRAQMRAf/EAGMAAQEBAAAAAAAAAAAAAAAAAAEFBAEBAAAAAAAAAAAAAAAAAAAAABAAAgECBAcAAAAAAAAAAAAAAREAITFRQWECcZGxwdHhEgMTUoGhIjJCYnKSI//Z",
  walnut:
    "data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAZABkAAD/7AARRHVja3kAAQAEAAAAPAAA/+4ADkFkb2JlAGTAAAAAAf/bAIQABgQEBAUEBgUFBgkGBQYJCwgGBggLDAoKCwoKDBAMDAwMDAwQDA4PEA8ODBMTFBQTExwbGxscHx8fHx8fHx8fHwEHBwcNDA0YEBAYGhURFRofHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8f/8AAEQgAQABAAwERAAIRAQMRAf/EAF8AAQEBAAAAAAAAAAAAAAAAAAEGBAEBAAAAAAAAAAAAAAAAAAAAABAAAQUBAAAAAAAAAAAAAAAAESExQVFhgZGxwdHhMlLwgqEiI3ETEgABAgUCBwAAAAAAAAAAAAERADFBYSExkUEgUXGBobHB0SJCUv/9",
  mahogany:
    "data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAZABkAAD/7AARRHVja3kAAQAEAAAAPAAA/+4ADkFkb2JlAGTAAAAAAf/bAIQABgQEBAUEBgUFBgkGBQYJCwgGBggLDAoKCwoKDBAMDAwMDAwQDA4PEA8ODBMTFBQTExwbGxscHx8fHx8fHx8fHwEHBwcNDA0YEBAYGhURFRofHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8f/8AAEQgAQABAAwERAAIRAQMRAf/EAGEAAQEBAAAAAAAAAAAAAAAAAAEGBQEBAAAAAAAAAAAAAAAAAAAAABAAAgECBAcAAAAAAAAAAAAAAREAITFRQWECcZGxwdHhEgMTUoGhIjJCYnKSE0MUBQE3c4Kj/9",
  cherry:
    "data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAZABkAAD/7AARRHVja3kAAQAEAAAAPAAA/+4ADkFkb2JlAGTAAAAAAf/bAIQABgQEBAUEBgUFBgkGBQYJCwgGBggLDAoKCwoKDBAMDAwMDAwQDA4PEA8ODBMTFBQTExwbGxscHx8fHx8fHx8fHwEHBwcNDA0YEBAYGhURFRofHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8f/8AAEQgAQABAAwERAAIRAQMRAf/EAGIAAQEBAAAAAAAAAAAAAAAAAAEGBQEBAAAAAAAAAAAAAAAAAAAAABAAAgICBQUAAAAAAAAAAAAAAREAITFRQWFxgZGx0eESEzJSoSJCYpIjMwQFBxc3OCo4/9",
  teak: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAZABkAAD/7AARRHVja3kAAQAEAAAAPAAA/+4ADkFkb2JlAGTAAAAAAf/bAIQABgQEBAUEBgUFBgkGBQYJCwgGBggLDAoKCwoKDBAMDAwMDAwQDA4PEA8ODBMTFBQTExwbGxscHx8fHx8fHx8fHwEHBwcNDA0YEBAYGhURFRofHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8f/8AAEQgAQABAAwERAAIRAQMRAf/EAGAAAQEBAAAAAAAAAAAAAAAAAAEGBAEBAAAAAAAAAAAAAAAAAAAAABAAAgECBQUAAAAAAAAAAAAAAREAITFRQWFxgZGx0eESEzJSoSJCYpIjEwQFBxc3OCo4ST/9",
}

const FABRIC_TEXTURES = {
  leather:
    "data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAZABkAAD/7AARRHVja3kAAQAEAAAAPAAA/+4ADkFkb2JlAGTAAAAAAf/bAIQABgQEBAUEBgUFBgkGBQYJCwgGBggLDAoKCwoKDBAMDAwMDAwQDA4PEA8ODBMTFBQTExwbGxscHx8fHx8fHx8fHwEHBwcNDA0YEBAYGhURFRofHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8f/8AAEQgAQABAAwERAAIRAQMRAf/EAGQAAQEBAAAAAAAAAAAAAAAAAAEGBAEBAAAAAAAAAAAAAAAAAAAAABAAAgECBQUAAAAAAAAAAAAAAREAITFRQWFxgZGx0eESEzJSoSJCYpIjEwQFBxc3OCo4SRAAAgUCBwAAAAAAAAAAAAERADFBYSExkUEgUXGBobHB0SJCUv/9",
  velvet:
    "data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAZABkAAD/7AARRHVja3kAAQAEAAAAPAAA/+4ADkFkb2JlAGTAAAAAAf/bAIQABgQEBAUEBgUFBgkGBQYJCwgGBggLDAoKCwoKDBAMDAwMDAwQDA4PEA8ODBMTFBQTExwbGxscHx8fHx8fHx8fHwEHBwcNDA0YEBAYGhURFRofHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8f/8AAEQgAQABAAwERAAIRAQMRAf/EAGMAAQEBAAAAAAAAAAAAAAAAAAEGBAEBAAAAAAAAAAAAAAAAAAAAABAAAgECBAcAAAAAAAAAAAAAAREAITFRQWECcZGxwdHhEgMTUoGhIjJCYnKSI//Z",
  cotton:
    "data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAZABkAAD/7AARRHVja3kAAQAEAAAAPAAA/+4ADkFkb2JlAGTAAAAAAf/bAIQABgQEBAUEBgUFBgkGBQYJCwgGBggLDAoKCwoKDBAMDAwMDAwQDA4PEA8ODBMTFBQTExwbGxscHx8fHx8fHx8fHwEHBwcNDA0YEBAYGhURFRofHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8f/8AAEQgAQABAAwERAAIRAQMRAf/EAF8AAQEBAAAAAAAAAAAAAAAAAAEGBAEBAAAAAAAAAAAAAAAAAAAAABAAAQUBAAAAAAAAAAAAAAAAESExQVFhgZGxwdHhMlLwgqEiI3ETEgABAgUCBwAAAAAAAAAAAAERADFBYSExkUEgUXGBobHB0SJCUv/9",
  linen:
    "data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAZABkAAD/7AARRHVja3kAAQAEAAAAPAAA/+4ADkFkb2JlAGTAAAAAAf/bAIQABgQEBAUEBgUFBgkGBQYJCwgGBggLDAoKCwoKDBAMDAwMDAwQDA4PEA8ODBMTFBQTExwbGxscHx8fHx8fHx8fHwEHBwcNDA0YEBAYGhURFRofHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8f/8AAEQgAQABAAwERAAIRAQMRAf/EAGEAAQEBAAAAAAAAAAAAAAAAAAEGBQEBAAAAAAAAAxxxxxxxxx0eESEzJSoSJCYpIjMwQFBxc3OCo4/9",
  silk: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAZABkAAD/7AARRHVja3kAAQAEAAAAPAAA/+4ADkFkb2JlAGTAAAAAAf/bAIQABgQEBAUEBgUFBgkGBQYJCwgGBggLDAoKCwoKDBAMDAwMDAwQDA4PEA8ODBMTFBQTExwbGxscHx8fHx8fHx8fHwEHBwcNDA0YEBAYGhURFRofHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8f/8AAEQgAQABAAwERAAIRAQMRAf/EAGIAAQEBAAAAAAAAAAAAAAAAAAEGBQEBAAAAAAAAAAAAAAAAAAAAABAAAgICBQUAAAAAAAAAAAAAAREAITFRQWFxgZGx0eESEzJSoSJCYpIjMwQFBxc3OCo4/9",
}

export function useWoodTexture(woodType: string) {
  const texture = useLoader(
    TextureLoader,
    WOOD_GRAIN_TEXTURES[woodType as keyof typeof WOOD_GRAIN_TEXTURES] || WOOD_GRAIN_TEXTURES.oak,
  )

  return useMemo(() => {
    texture.wrapS = texture.wrapT = RepeatWrapping
    texture.repeat.set(4, 4)
    return texture
  }, [texture])
}

export function useFabricTexture(fabricType: string) {
  const texture = useLoader(
    TextureLoader,
    FABRIC_TEXTURES[fabricType as keyof typeof FABRIC_TEXTURES] || FABRIC_TEXTURES.cotton,
  )

  return useMemo(() => {
    texture.wrapS = texture.wrapT = RepeatWrapping
    texture.repeat.set(8, 8)
    return texture
  }, [texture])
}

export function useLeatherTexture() {
  const texture = useLoader(TextureLoader, FABRIC_TEXTURES.leather)

  return useMemo(() => {
    texture.wrapS = texture.wrapT = RepeatWrapping
    texture.repeat.set(2, 2)
    return texture
  }, [texture])
}
